import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:tajalwaqaracademy/features/TeachersManagement/domain/usecases/get_teacher_by_id.dart';

// Import your features' use cases and BLoCs here.
// Grouping by feature improves readability.
import 'package:tajalwaqaracademy/features/TeachersManagement/domain/usecases/get_teachers.dart';
import 'package:tajalwaqaracademy/features/TeachersManagement/presentation/bloc/teacher_bloc.dart';
import 'package:tajalwaqaracademy/features/auth/domain/usecases/check_login_usecase.dart';
import 'package:tajalwaqaracademy/features/auth/domain/usecases/forget_password_usecase.dart';
import 'package:tajalwaqaracademy/features/auth/domain/usecases/login_usecase.dart';
import 'package:tajalwaqaracademy/features/auth/domain/usecases/logout_usecase.dart';
import 'package:tajalwaqaracademy/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:tajalwaqaracademy/features/auth/presentation/bloc/auth_event.dart';

import '../../features/StudentsManagement/domain/usecases/delete_student_usecase.dart';
import '../../features/StudentsManagement/domain/usecases/fetch_more_student_usecase.dart';
import '../../features/StudentsManagement/domain/usecases/get_student_by_id.dart';
import '../../features/StudentsManagement/domain/usecases/get_students.dart';
import '../../features/StudentsManagement/domain/usecases/set_student_status_params.dart';
import '../../features/StudentsManagement/domain/usecases/upsert_student_usecase.dart';
import '../../features/StudentsManagement/presentation/bloc/student_bloc.dart';
import '../../features/TeachersManagement/domain/usecases/delete_teacher_usecase.dart';
import '../../features/TeachersManagement/domain/usecases/fetch_more_teachers_usecase.dart';
import '../../features/TeachersManagement/domain/usecases/set_teacher_status_params.dart';
import '../../features/TeachersManagement/domain/usecases/upsert_teacher_usecase.dart';
import 'injection.config.dart'; // This is auto-generated by build_runner

/// The global service locator instance for dependency injection.
final sl = GetIt.instance;

/// A DI module specifically for registering BLoCs that require
/// initial event dispatching or custom instantiation logic.
@module
abstract class BlocModule {
  /// Provides the [AuthBloc] and immediately dispatches [AppStarted].
  ///
  /// This pattern is useful for triggering initial data fetches or state
  /// checks as soon as the BLoC is first requested by the UI.
  @factoryMethod
  AuthBloc authBloc(
    LoginUseCase loginUC,
    CheckLoginUseCase checkLoginUC,
    LogoutUseCase logoutUC,
    ForgetPasswordUseCase forgetPasswordUC,
  ) {
    // The cascade operator (..) allows us to call a method on the new instance
    // before returning it, making initial event dispatching clean.
    return AuthBloc(loginUC, checkLoginUC, logoutUC, forgetPasswordUC)
      ..add(AppStarted());
  }

  /// Provides the [TeacherBloc] and immediately dispatches [FetchAllTeachersEvent]
  /// to pre-fetch data.
  @factoryMethod
  TeacherBloc teacherBloc(
    WatchTeachersUseCase watchTeachers,
    FetchMoreTeachersUseCase fetchMoreTeachers,
    UpsertTeacher upsertTeacher,
    DeleteTeacherUseCase deleteTeacher,
    GetTeacherById getTeacherById,
    SetTeacherStatusUseCase setTeacherStatus,
  ) {
    return TeacherBloc(
      watchTeachers: watchTeachers,
      fetchMoreTeachers: fetchMoreTeachers,
      upsertTeacher: upsertTeacher,
      deleteTeacher: deleteTeacher,
      getTeacherById: getTeacherById,
      setTeacherStatus: setTeacherStatus,
    )..add(const WatchTeachersStarted());
  }

  /// Provides the [StudentBloc] and immediately dispatches [FetchAllStudentsEvent]
  /// to pre-fetch data.
  @factoryMethod
  StudentBloc studentBloc(
    WatchStudentsUseCase watchStudents,
    FetchMoreStudentsUseCase fetchMoreStudents,
    UpsertStudent upsertStudent,
    DeleteStudentUseCase deleteStudent,
    GetStudentById getStudentById,
    SetStudentStatusUseCase setStudentStatus,
  ) {
    return StudentBloc(
      watchStudents: watchStudents,
      fetchMoreStudents: fetchMoreStudents,
      upsertStudent: upsertStudent,
      deleteStudent: deleteStudent,
      getStudentById: getStudentById,
      setStudentStatus: setStudentStatus,
    )..add(const WatchStudentsStarted());
  }
}

/// Initializes the dependency injection container for the application.
///
/// This function orchestrates the auto-generated registration logic from
/// `injectable`. It should be called once in `main.dart` before `runApp`.
@injectableInit
Future<void> configureDependencies() => sl.init();
