import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

// Import your features' use cases and BLoCs here.
// Grouping by feature improves readability.

import '../../features/StudentsManagement/domain/usecases/delete_student_usecase.dart';
import '../../features/StudentsManagement/domain/usecases/fetch_more_student_usecase.dart';
import '../../features/StudentsManagement/domain/usecases/generate_follow_up_report_use_case.dart';
import '../../features/StudentsManagement/domain/usecases/get_filtered_students.dart';
import '../../features/StudentsManagement/domain/usecases/get_student_by_id.dart';
import '../../features/StudentsManagement/domain/usecases/get_students.dart';
import '../../features/StudentsManagement/domain/usecases/set_student_status_params.dart';
import '../../features/StudentsManagement/domain/usecases/upsert_student_usecase.dart';
import '../../features/StudentsManagement/presentation/bloc/student_bloc.dart';
import '../../features/TeachersManagement/domain/usecases/delete_teacher_usecase.dart';
import '../../features/TeachersManagement/domain/usecases/fetch_more_teachers_usecase.dart';
import '../../features/TeachersManagement/domain/usecases/get_teacher_by_id.dart';
import '../../features/TeachersManagement/domain/usecases/get_teachers.dart';
import '../../features/TeachersManagement/domain/usecases/set_teacher_status_params.dart';
import '../../features/TeachersManagement/domain/usecases/upsert_teacher_usecase.dart';
import '../../features/TeachersManagement/presentation/bloc/teacher_bloc.dart';
import '../../features/app/cubit/app_setup_cubit.dart';
import '../../features/auth/domain/usecases/check_login_usecase.dart';
import '../../features/auth/domain/usecases/forget_password_usecase.dart';
import '../../features/auth/domain/usecases/login_usecase.dart';
import '../../features/auth/domain/usecases/logout_usecase.dart';
import '../../features/auth/presentation/bloc/auth_bloc.dart';
import '../../features/daily_tracking/domain/usecases/finalize_session.dart';
import '../../features/daily_tracking/domain/usecases/get_all_mistakes.dart';
import '../../features/daily_tracking/domain/usecases/get_or_create_today_tracking.dart';
import '../../features/daily_tracking/domain/usecases/get_mistakes_ayahs.dart';
import '../../features/daily_tracking/domain/usecases/get_page_data.dart';
import '../../features/daily_tracking/domain/usecases/get_surahs_list.dart';
import '../../features/daily_tracking/domain/usecases/save_task_progress.dart';
import '../../features/daily_tracking/presentation/bloc/quran_reader_bloc.dart';
import '../../features/daily_tracking/presentation/bloc/tracking_session_bloc.dart';
import '../../features/settings/domain/usecases/get_latest_policy_usecase.dart';
import '../../features/settings/domain/usecases/get_settings.dart';
import '../../features/settings/domain/usecases/get_user_profile.dart';
import '../../features/settings/domain/usecases/save_theme.dart';
import '../../features/settings/domain/usecases/set_analytics_preference.dart';
import '../../features/settings/domain/usecases/set_notifications_preference.dart';
import '../../features/settings/domain/usecases/update_user_profile.dart';
import '../../features/settings/presentation/bloc/settings_bloc.dart';
import 'injection.config.dart'; // This is auto-generated by build_runner

/// The global service locator instance for dependency injection.
final sl = GetIt.instance;

/// A DI module specifically for registering BLoCs that require
/// initial event dispatching or custom instantiation logic.
@module
abstract class BlocModule {
  /// Provides the [AuthBloc] and immediately dispatches [AppStarted].
  ///
  /// This pattern is useful for triggering initial data fetches or state
  /// checks as soon as the BLoC is first requested by the UI.
  @factoryMethod
  AuthBloc authBloc(
    LogInUseCase logInUC,
    CheckLogInUseCase checkLogInUC,
    LogOutUseCase logOutUC,
    ForgetPasswordUseCase forgetPasswordUC,
  ) {
    // The cascade operator (..) allows us to call a method on the new instance
    // before returning it, making initial event dispatching clean.
    return AuthBloc(logInUC, checkLogInUC, logOutUC, forgetPasswordUC);
  }

  /// Provides the [TeacherBloc] and immediately dispatches [FetchAllTeachersEvent]
  /// to pre-fetch data.
  @factoryMethod
  AppSetupCubit appSetupCubit() => AppSetupCubit();
  @factoryMethod
  TeacherBloc teacherBloc(
    WatchTeachersUseCase watchTeachers,
    FetchMoreTeachersUseCase fetchMoreTeachers,
    UpsertTeacher upsertTeacher,
    DeleteTeacherUseCase deleteTeacher,
    GetTeacherById getTeacherById,
    SetTeacherStatusUseCase setTeacherStatus,
  ) {
    return TeacherBloc(
      watchTeachers: watchTeachers,
      fetchMoreTeachers: fetchMoreTeachers,
      upsertTeacher: upsertTeacher,
      deleteTeacher: deleteTeacher,
      getTeacherById: getTeacherById,
      setTeacherStatus: setTeacherStatus,
    )..add(const WatchTeachersStarted());
  }

  /// Provides the [StudentBloc] and immediately dispatches [FetchAllStudentsEvent]
  /// to pre-fetch data.
  @factoryMethod
  StudentBloc studentBloc(
    WatchStudentsUseCase watchStudents,
    FetchMoreStudentsUseCase fetchMoreStudents,
    FetchFilteredStudentsUseCase fetchFilteredStudents,
    UpsertStudent upsertStudent,
    DeleteStudentUseCase deleteStudent,
    GetStudentById getStudentById,
    SetStudentStatusUseCase setStudentStatus,
    GenerateFollowUpReportUseCase generateFollowUpReportUC,
  ) {
    return StudentBloc(
      watchStudents: watchStudents,
      fetchMoreStudents: fetchMoreStudents,
      fetchFilteredStudents: fetchFilteredStudents,
      upsertStudent: upsertStudent,
      deleteStudent: deleteStudent,
      getStudentById: getStudentById,
      setStudentStatus: setStudentStatus,
      generateFollowUpReportUC: generateFollowUpReportUC,
    )..add(const WatchStudentsStarted());
  }

  /// Provides the [QuranReaderBloc] and immediately dispatches [SurahsListRequested]
  /// to pre-fetch data.
  QuranReaderBloc quranReaderBloc(
    GetSurahsList getSurahsList,
    GetMistakesAyahs getMistakesAyahs,
    GetPageData getPageData,
  ) {
    return QuranReaderBloc(
      getPageData: getPageData,
      getMistakesAyahs : getMistakesAyahs,
      getSurahsList: getSurahsList,
    )..add(SurahsListRequested());
  }


  /// Provides the [SettingsBloc] and immediately dispatches [LoadInitialSettings]
  /// to pre-fetch data.
  SettingsBloc settingsBloc(
    GetSettings getSettings,
    SaveTheme saveTheme,
    SetNotificationsPreference setNotificationsPreference,
    SetAnalyticsPreference setAnalyticsPreference,
    GetUserProfile getUserProfile,
    UpdateUserProfile updateUserProfile,
    GetLatestPolicyUseCase getLatestPolicy,
  ) {
    return SettingsBloc(
      getSettings: getSettings,
      getLatestPolicy: getLatestPolicy,
      saveTheme: saveTheme,
      setNotificationsPreference: setNotificationsPreference,
      setAnalyticsPreference: setAnalyticsPreference,
      getUserProfile: getUserProfile,
      updateUserProfile: updateUserProfile,
    )..add(LoadInitialSettings());
  }

  /// Provides the [TrackingSessionBloc] and immediately dispatches [SessionStarted]
  /// to pre-fetch data.
  TrackingSessionBloc trackingSession(
    GetOrCreateTodayTrackingDetails getOrCreateTodayTrackingDetails,
    SaveTaskProgress saveTaskProgress,
    FinalizeSession finalizeSession,
    GetAllMistakes getAllMistakes,
  ) {
    return TrackingSessionBloc(
      getOrCreateTodayTrackingDetails: getOrCreateTodayTrackingDetails,
      saveTaskProgress: saveTaskProgress,
      finalizeSession: finalizeSession,
      getAllMistakes: getAllMistakes,
    );
  }
}

/// Initializes the dependency injection container for the application.
///
/// This function orchestrates the auto-generated registration logic from
/// `injectable`. It should be called once in `main.dart` before `runApp`.
@injectableInit
Future<void> configureDependencies() => sl.init();


// injectable library commands :
// to refresh do this `flutter pub run build_runner build --delete-conflicting-outputs`
// to watch for changes do this `flutter pub run build_runner watch --delete-conflicting-outputs`
// to clean the build cache do this `flutter pub run build_runner clean`