import 'package:tajalwaqaracademy/core/models/countery_model.dart';


List<CountryModel> countries = [
  CountryModel(
    id: "0",
    name: "Greece",
    status: "GR",
    arabicName: "اليونان",
    countryCallingCode: "30",
  ),
  CountryModel(
    id: "1",
    name: "Afghanistan",
    status: "AF",
    arabicName: "أفغانستان",
    countryCallingCode: "93",
  ),
  CountryModel(
    id: "2",
    name: "Aland Islands",
    status: "AX",
    arabicName: "جزر اولاند",
    countryCallingCode: "358 18",
  ),
  CountryModel(
    id: "3",
    name: "Albania",
    status: "AL",
    arabicName: "ألبانيا",
    countryCallingCode: "355",
  ),

  CountryModel(
    id: "4",
    name: "Algeria",
    status: "DZ",
    arabicName: "الجزائر",
    countryCallingCode: "213",
  ),
  CountryModel(
    id: "5",
    name: "American Samoa",
    status: "AS",
    arabicName: "ساموا الأمريكية",
    countryCallingCode: "1 684",
  ),
  CountryModel(
    id: "6",
    name: "Andorra",
    status: "AD",
    arabicName: "أندورا",
    countryCallingCode: "376",
  ),
  CountryModel(
    id: "7",
    name: "Angola",
    status: "AO",
    arabicName: "أنغولا",
    countryCallingCode: "244",
  ),
  CountryModel(
    id: "8",
    name: "Anguilla",
    status: "AI",
    arabicName: "أنغويلا",
    countryCallingCode: "1 264",
  ),
  CountryModel(
    id: "9",
    name: "Antarctica",
    status: "AQ",
    arabicName: "القارة القطبية الجنوبية",
    countryCallingCode: "672 1",
  ),
  CountryModel(
    id: "10",
    name: "Antigua And Barbuda",
    status: "AG",
    arabicName: "انتيغا وباربودا",
    countryCallingCode: "1 268",
  ),
  CountryModel(
    id: "11",
    name: "Argentina",
    status: "AR",
    arabicName: "الأرجنتين",
    countryCallingCode: "54",
  ),
  CountryModel(
    id: "12",
    name: "Armenia",
    status: "AM",
    arabicName: "أرمينيا",
    countryCallingCode: "374",
  ),
  CountryModel(
    id: "13",
    name: "Aruba",
    status: "AW",
    arabicName: "أروبا",
    countryCallingCode: "297",
  ),
  CountryModel(
    id: "14",
    name: "Australia",
    status: "AU",
    arabicName: "أستراليا",
    countryCallingCode: "61",
  ),
  CountryModel(
    id: "15",
    name: "Austria",
    status: "AT",
    arabicName: "النمسا",
    countryCallingCode: "43",
  ),
  CountryModel(
    id: "16",
    name: "Azerbaijan",
    status: "AZ",
    arabicName: "أذربيجان",
    countryCallingCode: "994",
  ),
  CountryModel(
    id: "17",
    name: "Bahamas",
    status: "BS",
    arabicName: "جزر البهاماس",
    countryCallingCode: "1 242",
  ),
  CountryModel(
    id: "18",
    name: "Bahrain",
    status: "BH",
    arabicName: "البحرين",
    countryCallingCode: "973",
  ),
  CountryModel(
    id: "19",
    name: "Bangladesh",
    status: "BD",
    arabicName: "بنغلادش",
    countryCallingCode: "880",
  ),
  CountryModel(
    id: "20",
    name: "Barbados",
    status: "BB",
    arabicName: "باربادوس",
    countryCallingCode: "1 246",
  ),
  CountryModel(
    id: "21",
    name: "Belarus",
    status: "BY",
    arabicName: "بيلاروسيا",
    countryCallingCode: "375",
  ),
  CountryModel(
    id: "22",
    name: "Belgium",
    status: "BE",
    arabicName: "بلجيكا",
    countryCallingCode: "32",
  ),
  CountryModel(
    id: "23",
    name: "Belize",
    status: "BZ",
    arabicName: "بليز",
    countryCallingCode: "501",
  ),
  CountryModel(
    id: "24",
    name: "Benin",
    status: "BJ",
    arabicName: "بنين",
    countryCallingCode: "229",
  ),
  CountryModel(
    id: "25",
    name: "Bermuda",
    status: "BM",
    arabicName: "برمودا",
    countryCallingCode: "1 441",
  ),
  CountryModel(
    id: "26",
    name: "Bhutan",
    status: "BT",
    arabicName: "بوتان",
    countryCallingCode: "975",
  ),
  CountryModel(
    id: "27",
    name: "Bolivia",
    status: "BO",
    arabicName: "بوليفيا",
    countryCallingCode: "591",
  ),
  CountryModel(
    id: "28",
    name: "Bosnia and Herzegovina",
    status: "BA",
    arabicName: "البوسنة والهرسك",
    countryCallingCode: "387",
  ),
  CountryModel(
    id: "29",
    name: "Botswana",
    status: "BW",
    arabicName: "بوتسوانا",
    countryCallingCode: "267",
  ),
  CountryModel(
    id: "30",
    name: "Bouvet Island",
    status: "BV",
    arabicName: "جزيرة بوفيه",
    countryCallingCode: "47",
  ),
  CountryModel(
    id: "31",
    name: "Brazil",
    status: "BR",
    arabicName: "البرازيل",
    countryCallingCode: "55",
  ),
  CountryModel(
    id: "32",
    name: "",
    status: "IO",
    arabicName: "إقليم المحيط البريطاني الهندي",
    countryCallingCode: "246",
  ),
  CountryModel(
    id: "33",
    name: "Brunei Darussalam",
    status: "BN",
    arabicName: "بروناي دار السلام",
    countryCallingCode: "673",
  ),
  CountryModel(
    id: "34",
    name: "Bulgaria",
    status: "BG",
    arabicName: "بلغاريا",
    countryCallingCode: "359",
  ),
  CountryModel(
    id: "35",
    name: "Burkina Faso",
    status: "BF",
    arabicName: "بوركينا فاسو",
    countryCallingCode: "226",
  ),
  CountryModel(
    id: "36",
    name: "Burundi",
    status: "BI",
    arabicName: "بوروندي",
    countryCallingCode: "257",
  ),
  CountryModel(
    id: "37",
    name: "Cambodia",
    status: "KH",
    arabicName: "كمبوديا",
    countryCallingCode: "855",
  ),
  CountryModel(
    id: "38",
    name: "Cameroon",
    status: "CM",
    arabicName: "الكاميرون",
    countryCallingCode: "237",
  ),
  CountryModel(
    id: "39",
    name: "Canada",
    status: "CA",
    arabicName: "كندا",
    countryCallingCode: "1",
  ),
  CountryModel(
    id: "40",
    name: "Cape Verde",
    status: "CV",
    arabicName: "الرأس الأخضر",
    countryCallingCode: "238",
  ),
  CountryModel(
    id: "41",
    name: "Cayman Islands",
    status: "KY",
    arabicName: "جزر كايمان",
    countryCallingCode: "1 345",
  ),
  CountryModel(
    id: "42",
    name: "Central African Republic",
    status: "CF",
    arabicName: "جمهورية أفريقيا الوسطى",
    countryCallingCode: "236",
  ),
  CountryModel(
    id: "43",
    name: "Chad",
    status: "TD",
    arabicName: "تشاد",
    countryCallingCode: "235",
  ),
  CountryModel(
    id: "44",
    name: "Chile",
    status: "CL",
    arabicName: "تشيلي",
    countryCallingCode: "56",
  ),
  CountryModel(
    id: "45",
    name: "China",
    status: "CN",
    arabicName: "الصين",
    countryCallingCode: "86",
  ),
  CountryModel(
    id: "46",
    name: "Christmas Island",
    status: "CX",
    arabicName: "جزيرة الكريسماس",
    countryCallingCode: "61 89164",
  ),
  CountryModel(
    id: "47",
    name: "Cocos(Keeling)Islands",
    status: "CC",
    arabicName: "جزر كوكوس (كيلينغ)",
    countryCallingCode: "61 89162",
  ),
  CountryModel(
    id: "48",
    name: "Colombia",
    status: "CO",
    arabicName: "كولومبيا",
    countryCallingCode: "57",
  ),
  CountryModel(
    id: "49",
    name: "Comoros",
    status: "KM",
    arabicName: "جزر القمر",
    countryCallingCode: "269",
  ),
  CountryModel(
    id: "50",
    name: "Congo",
    status: "CG",
    arabicName: "الكونغو",
    countryCallingCode: "242",
  ),
  CountryModel(
    id: "51",
    name: "Democratic Republic Of Congo",
    status: "CD",
    arabicName: "جمهورية الكونغو الديمقراطية",
    countryCallingCode: "243",
  ),
  CountryModel(
    id: "52",
    name: "Cook Islands",
    status: "CK",
    arabicName: "جزر كوك",
    countryCallingCode: "682",
  ),
  CountryModel(
    id: "53",
    name: "Costa Rica",
    status: "CR",
    arabicName: "كوستاريكا",
    countryCallingCode: "506",
  ),
  CountryModel(
    id: "54",
    name: "Cote D'Ivoire (Ivory Coast)",
    status: "CI",
    arabicName: "كوت ديفوار (ساحل العاج)",
    countryCallingCode: "225",
  ),
  CountryModel(
    id: "55",
    name: "Croatia (Hrvatska)",
    status: "HR",
    arabicName: "كرواتيا (هرفاتسكا)",
    countryCallingCode: "385",
  ),
  CountryModel(
    id: "56",
    name: "Cuba",
    status: "CU",
    arabicName: "كوبا",
    countryCallingCode: "53",
  ),
  CountryModel(
    id: "57",
    name: "Cyprus",
    status: "CY",
    arabicName: "قبرص",
    countryCallingCode: "357",
  ),
  CountryModel(
    id: "58",
    name: "Czech Republic",
    status: "CZ",
    arabicName: "الجمهورية التشيكية",
    countryCallingCode: "420",
  ),
  CountryModel(
    id: "59",
    name: "Denmark",
    status: "DK",
    arabicName: "الدانمارك",
    countryCallingCode: "45",
  ),
  CountryModel(
    id: "60",
    name: "Djibouti",
    status: "DJ",
    arabicName: "جيبوتي",
    countryCallingCode: "253",
  ),
  CountryModel(
    id: "61",
    name: "Dominica",
    status: "DM",
    arabicName: "الدومينكان",
    countryCallingCode: "1 767",
  ),
  CountryModel(
    id: "62",
    name: "Dominican Republic",
    status: "DO",
    arabicName: "جمهورية الدومينيكان",
    countryCallingCode: "809",
  ),
  CountryModel(
    id: "63",
    name: "East Timor",
    status: "TL",
    arabicName: "تيمور الشرقية",
    countryCallingCode: "670",
  ),
  CountryModel(
    id: "64",
    name: "Ecuador",
    status: "EC",
    arabicName: "الإكوادور",
    countryCallingCode: "593",
  ),
  CountryModel(
    id: "65",
    name: "Egypt",
    status: "EG",
    arabicName: "مصر",
    countryCallingCode: "20",
  ),
  CountryModel(
    id: "66",
    name: "El Salvador",
    status: "SV",
    arabicName: "السلفادور",
    countryCallingCode: "503",
  ),
  CountryModel(
    id: "67",
    name: "Equatorial Guinea",
    status: "GQ",
    arabicName: "غينيا الاستوائية",
    countryCallingCode: "240",
  ),
  CountryModel(
    id: "68",
    name: "Eritrea",
    status: "ER",
    arabicName: "إريتريا",
    countryCallingCode: "291",
  ),
  CountryModel(
    id: "69",
    name: "Estonia",
    status: "EE",
    arabicName: "إستونيا",
    countryCallingCode: "372",
  ),
  CountryModel(
    id: "70",
    name: "Ethiopia",
    status: "ET",
    arabicName: "إثيوبيا",
    countryCallingCode: "251",
  ),
  CountryModel(
    id: "71",
    name: "Falkland Islands",
    status: "FK",
    arabicName: "جزر فوكلاند",
    countryCallingCode: "500",
  ),
  CountryModel(
    id: "72",
    name: "Faroe Islands",
    status: "FO",
    arabicName: "جزر فاروس",
    countryCallingCode: "298",
  ),
  CountryModel(
    id: "73",
    name: "Fiji Islands",
    status: "FJ",
    arabicName: "جزر فيجي",
    countryCallingCode: "679",
  ),
  CountryModel(
    id: "74",
    name: "Finland",
    status: "FI",
    arabicName: "فنلندا",
    countryCallingCode: "358",
  ),
  CountryModel(
    id: "75",
    name: "France",
    status: "FR",
    arabicName: "فرنسا",
    countryCallingCode: "33",
  ),
  CountryModel(
    id: "76",
    name: "French Guiana",
    status: "GF",
    arabicName: "غيانا الفرنسية",
    countryCallingCode: "594",
  ),
  CountryModel(
    id: "77",
    name: "French Polynesia",
    status: "PF",
    arabicName: "بولينيزيا الفرنسية",
    countryCallingCode: "689",
  ),
  CountryModel(
    id: "78",
    name: "French Southern Territories",
    status: "TF",
    arabicName: "المناطق الجنوبية لفرنسا",
    countryCallingCode: "262",
  ),
  CountryModel(
    id: "79",
    name: "Gabon",
    status: "GA",
    arabicName: "الغابون",
    countryCallingCode: "241",
  ),
  CountryModel(
    id: "80",
    name: "Gambia",
    status: "GM",
    arabicName: "غامبيا",
    countryCallingCode: "220",
  ),
  CountryModel(
    id: "81",
    name: "Georgia",
    status: "GE",
    arabicName: "جورجيا",
    countryCallingCode: "995",
  ),
  CountryModel(
    id: "82",
    name: "Germany",
    status: "DE",
    arabicName: "ألمانيا",
    countryCallingCode: "49",
  ),
  CountryModel(
    id: "83",
    name: "Ghana",
    status: "GH",
    arabicName: "غانا",
    countryCallingCode: "233",
  ),
  CountryModel(
    id: "84",
    name: "Gibraltar",
    status: "GI",
    arabicName: "جبل طارق",
    countryCallingCode: "350",
  ),
  CountryModel(
    id: "85",
    name: "Gibraltar",
    status: "GI",
    arabicName: "جبل طارق",
    countryCallingCode: "350",
  ),
  CountryModel(
    id: "86",
    name: "Greenland",
    status: "GL",
    arabicName: "جرينلاند",
    countryCallingCode: "299",
  ),
  CountryModel(
    id: "87",
    name: "Grenada",
    status: "GD",
    arabicName: "غرينادا",
    countryCallingCode: "473",
  ),
  CountryModel(
    id: "88",
    name: "Guadeloupe",
    status: "GP",
    arabicName: "جوادلوب",
    countryCallingCode: "590",
  ),
  CountryModel(
    id: "89",
    name: "Guam",
    status: "GU",
    arabicName: "غوام",
    countryCallingCode: "1 671",
  ),
  CountryModel(
    id: "90",
    name: "Guatemala",
    status: "GT",
    arabicName: "غواتيمالا",
    countryCallingCode: "502",
  ),
  CountryModel(
    id: "91",
    name: "Guernsey and Alderney",
    status: "GG",
    arabicName: "آلدرني",
    countryCallingCode: " 44 1481",
  ),
  CountryModel(
    id: "92",
    name: "Guinea",
    status: "GN",
    arabicName: "غينيا",
    countryCallingCode: "675",
  ),
  CountryModel(
    id: "93",
    name: "Guinea-Bissau",
    status: "GW",
    arabicName: "غينيا بيساو",
    countryCallingCode: "245",
  ),
  CountryModel(
    id: "94",
    name: "Guyana",
    status: "GY",
    arabicName: "غيانا",
    countryCallingCode: "592",
  ),
  CountryModel(
    id: "95",
    name: "Haiti",
    status: "HT",
    arabicName: "هايتي",
    countryCallingCode: "509",
  ),
  CountryModel(
    id: "96",
    name: "Heard Island and McDonald Islands",
    status: "HN",
    arabicName: "جزيرة هيرد وجزر ماكدونالد",
    countryCallingCode: "504",
  ),
  CountryModel(
    id: "97",
    name: "Honduras",
    status: "HN",
    arabicName: "هندوراس",
    countryCallingCode: "504",
  ),
  CountryModel(
    id: "98",
    name: "Hong Kong S.A.R.",
    status: "HK",
    arabicName: "هونغ كونغ (مناطق جمهورية الصين الشعبية الإدارية الخاصة)",
    countryCallingCode: "582",
  ),
  CountryModel(
    id: "99",
    name: "Hungary",
    status: "HU",
    arabicName: "هنغاريا",
    countryCallingCode: "36",
  ),
  CountryModel(
    id: "100",
    name: "Iceland",
    status: "IS",
    arabicName: "أيسلندا",
    countryCallingCode: "354",
  ),
  CountryModel(
    id: "101",
    name: "India",
    status: "IN",
    arabicName: "الهند",
    countryCallingCode: "91",
  ),
  CountryModel(
    id: "102",
    name: "Indonesia",
    status: "ID",
    arabicName: "إندونيسيا",
    countryCallingCode: "62",
  ),
  CountryModel(
    id: "103",
    name: "Iran",
    status: "IR",
    arabicName: "إيران",
    countryCallingCode: "98",
  ),
  CountryModel(
    id: "104",
    name: "Iraq",
    status: "IQ",
    arabicName: "العراق",
    countryCallingCode: "964",
  ),
  CountryModel(
    id: "105",
    name: "Ireland",
    status: "IE",
    arabicName: "أيرلندا",
    countryCallingCode: "353",
  ),
  CountryModel(
    id: "106",
    name: "Ireland",
    status: "IE",
    arabicName: "أيرلندا",
    countryCallingCode: "353",
  ),
  CountryModel(
    id: "107",
    name: "Italy",
    status: "IT",
    arabicName: "إيطاليا",
    countryCallingCode: "39",
  ),
  CountryModel(
    id: "108",
    name: "Jamaica",
    status: "JM",
    arabicName: "جامايكا",
    countryCallingCode: "1 876",
  ),
  CountryModel(
    id: "109",
    name: "Japan",
    status: "JP",
    arabicName: "اليابان",
    countryCallingCode: "81",
  ),
  CountryModel(
    id: "110",
    name: "Jersey",
    status: "JE",
    arabicName: "جيرسي",
    countryCallingCode: "44 1534",
  ),
  CountryModel(
    id: "111",
    name: "Jordan",
    status: "JO",
    arabicName: "الأردن",
    countryCallingCode: "962",
  ),
  CountryModel(
    id: "112",
    name: "Kazakhstan",
    status: "KZ",
    arabicName: "كازاخستان",
    countryCallingCode: "997",
  ),
  CountryModel(
    id: "113",
    name: "Kenya",
    status: "KE",
    arabicName: "كينيا",
    countryCallingCode: "254",
  ),
  CountryModel(
    id: "114",
    name: "Kiribati",
    status: "KI",
    arabicName: "كيريباتي",
    countryCallingCode: "686",
  ),
  CountryModel(
    id: "115",
    name: "Korea North",
    status: "KR",
    arabicName: "كوريا الشمالية",
    countryCallingCode: "850",
  ),
  CountryModel(
    id: "116",
    name: "Korea South",
    status: "PK",
    arabicName: "كوريا الجنوبية",
    countryCallingCode: "82",
  ),
  CountryModel(
    id: "117",
    name: "Kuwait",
    status: "KW",
    arabicName: "الكويت",
    countryCallingCode: "965",
  ),
  CountryModel(
    id: "118",
    name: "Kyrgyzstan",
    status: "KG",
    arabicName: "قيرغيزستان",
    countryCallingCode: "996",
  ),
  CountryModel(
    id: "119",
    name: "Laos",
    status: "LA",
    arabicName: "لاوس",
    countryCallingCode: "856",
  ),
  CountryModel(
    id: "120",
    name: "Latvia",
    status: "LV",
    arabicName: "لاتفيا",
    countryCallingCode: "371",
  ),
  CountryModel(
    id: "121",
    name: "Lebanon",
    status: "LB",
    arabicName: "لبنان",
    countryCallingCode: "961",
  ),
  CountryModel(
    id: "122",
    name: "Lesotho",
    status: "LS",
    arabicName: "ليسوتو",
    countryCallingCode: "266",
  ),
  CountryModel(
    id: "123",
    name: "Liberia",
    status: "LR",
    arabicName: "ليبيريا",
    countryCallingCode: "231",
  ),
  CountryModel(
    id: "124",
    name: "Libya",
    status: "LY",
    arabicName: "ليبيا",
    countryCallingCode: "218",
  ),
  CountryModel(
    id: "125",
    name: "Liechtenstein",
    status: "LI",
    arabicName: "ليختنشتاين",
    countryCallingCode: "423",
  ),
  CountryModel(
    id: "126",
    name: "Lithuania",
    status: "LT",
    arabicName: "ليتوانيا",
    countryCallingCode: "370",
  ),
  CountryModel(
    id: "127",
    name: "Luxembourg",
    status: "LU",
    arabicName: "لوكسمبورغ",
    countryCallingCode: "352",
  ),
  CountryModel(
    id: "128",
    name: "Macau S.A.R.",
    status: "MO",
    arabicName: "ماكاو (مناطق جمهورية الصين الشعبية الإدارية الخاصة)",
    countryCallingCode: "853",
  ),
  CountryModel(
    id: "129",
    name: "Macedonia",
    status: "MK",
    arabicName: "مقدونيا",
    countryCallingCode: "389",
  ),
  CountryModel(
    id: "130",
    name: "Madagascar",
    status: "MG",
    arabicName: "مدغشقر",
    countryCallingCode: "261",
  ),
  CountryModel(
    id: "131",
    name: "Malawi",
    status: "MW",
    arabicName: "مالاوي",
    countryCallingCode: "265",
  ),
  CountryModel(
    id: "132",
    name: "Malaysia",
    status: "MY",
    arabicName: "ماليزيا",
    countryCallingCode: "60",
  ),
  CountryModel(
    id: "133",
    name: "Maldives",
    status: "MV",
    arabicName: "جزر المالديف",
    countryCallingCode: "960",
  ),
  CountryModel(
    id: "134",
    name: "Mali",
    status: "ML",
    arabicName: "مالي",
    countryCallingCode: "223",
  ),
  CountryModel(
    id: "135",
    name: "Malta",
    status: "MT",
    arabicName: "مالطا",
    countryCallingCode: "356",
  ),
  CountryModel(
    id: "136",
    name: "Man (Isle of)",
    status: "IM",
    arabicName: "مان (جزيرة)",
    countryCallingCode: "44",
  ),
  CountryModel(
    id: "137",
    name: "Marshall Islands",
    status: "MH",
    arabicName: "جزر مارشال",
    countryCallingCode: "692",
  ),
  CountryModel(
    id: "138",
    name: "Martinique",
    status: "MQ",
    arabicName: "مارتينيك",
    countryCallingCode: "596",
  ),
  CountryModel(
    id: "139",
    name: "Mauritania",
    status: "MR",
    arabicName: "موريتانيا",
    countryCallingCode: "222",
  ),
  CountryModel(
    id: "140",
    name: "Mauritius",
    status: "MU",
    arabicName: "موريشيوس",
    countryCallingCode: "230",
  ),
  CountryModel(
    id: "141",
    name: "Mayotte",
    status: "YT",
    arabicName: "مايوت",
    countryCallingCode: "262",
  ),
  CountryModel(
    id: "142",
    name: "Mexico",
    status: "MX",
    arabicName: "المكسيك",
    countryCallingCode: "52",
  ),
  CountryModel(
    id: "143",
    name: "Micronesia",
    status: "FM",
    arabicName: "ميكرونيزيا",
    countryCallingCode: "691",
  ),
  CountryModel(
    id: "144",
    name: "Moldova",
    status: "MD",
    arabicName: "مولدافيا",
    countryCallingCode: "373",
  ),
  CountryModel(
    id: "145",
    name: "Monaco",
    status: "MC",
    arabicName: "موناكو",
    countryCallingCode: "377",
  ),
  CountryModel(
    id: "146",
    name: "Mongolia",
    status: "MN",
    arabicName: "منغوليا",
    countryCallingCode: "976",
  ),
  CountryModel(
    id: "147",
    name: "Montenegro",
    status: "ME",
    arabicName: "الجبل الأسود",
    countryCallingCode: "382",
  ),
  CountryModel(
    id: "148",
    name: "Montserrat",
    status: "MS",
    arabicName: "مونتسيرات",
    countryCallingCode: "1 664",
  ),
  CountryModel(
    id: "149",
    name: "Morocco",
    status: "MA",
    arabicName: "المغرب",
    countryCallingCode: "212",
  ),
  CountryModel(
    id: "150",
    name: "Mozambique",
    status: "MZ",
    arabicName: "موزمبيق",
    countryCallingCode: "258",
  ),
  CountryModel(
    id: "151",
    name: "Myanmar",
    status: "MM",
    arabicName: "ميانمار",
    countryCallingCode: "95",
  ),
  CountryModel(
    id: "152",
    name: "Namibia",
    status: "NA",
    arabicName: "ناميبيا",
    countryCallingCode: "264",
  ),
  CountryModel(
    id: "153",
    name: "Nauru",
    status: "NR",
    arabicName: "ناورو",
    countryCallingCode: "674",
  ),
  CountryModel(
    id: "154",
    name: "Nepal",
    status: "NP",
    arabicName: "نيبال",
    countryCallingCode: "977",
  ),
  CountryModel(
    id: "155",
    name: "Bonaire, Sint Eustatius and Saba",
    status: "NL",
    arabicName: "الجزر الكاريبية الهولندية",
    countryCallingCode: "599",
  ),
  CountryModel(
    id: "156",
    name: "Netherlands ",
    status: "NL",
    arabicName: "هولندا",
    countryCallingCode: "31",
  ),
  CountryModel(
    id: "157",
    name: "New Caledonia",
    status: "NC",
    arabicName: "كاليدونيا الجديدة",
    countryCallingCode: "687",
  ),
  CountryModel(
    id: "158",
    name: "New Zealand",
    status: "NZ",
    arabicName: "نيوزيلندا",
    countryCallingCode: "64",
  ),
  CountryModel(
    id: "159",
    name: "Nicaragua",
    status: "NI",
    arabicName: "نيكاراغوا",
    countryCallingCode: "505",
  ),
  CountryModel(
    id: "160",
    name: "Niger",
    status: "NE",
    arabicName: "النيجر",
    countryCallingCode: "227",
  ),
  CountryModel(
    id: "161",
    name: "Nigeria",
    status: "NG",
    arabicName: "نيجيريا",
    countryCallingCode: "234",
  ),
  CountryModel(
    id: "162",
    name: "Niue",
    status: "NI",
    arabicName: "نيوي",
    countryCallingCode: "683",
  ),
  CountryModel(
    id: "163",
    name: "Norfolk Island",
    status: "NF",
    arabicName: "جزيرة نورفولك",
    countryCallingCode: "672 3",
  ),
  CountryModel(
    id: "164",
    name: "Northern Mariana Islands",
    status: "MP",
    arabicName: "جزر ماريانا الشمالية",
    countryCallingCode: "1 670",
  ),
  CountryModel(
    id: "165",
    name: "Norway",
    status: "NO",
    arabicName: "النرويج",
    countryCallingCode: "47",
  ),
  CountryModel(
    id: "166",
    name: "Oman",
    status: "OM",
    arabicName: "عمان",
    countryCallingCode: "968",
  ),
  CountryModel(
    id: "167",
    name: "Pakistan",
    status: "PK",
    arabicName: "باكستان",
    countryCallingCode: "92",
  ),
  CountryModel(
    id: "168",
    name: "Palau",
    status: "PW",
    arabicName: "بالاو",
    countryCallingCode: "680",
  ),
  CountryModel(
    id: "169",
    name: "Palestinian Territory Occupied",
    status: "PS",
    arabicName: "الأراضي الفلسطينية المحتلة",
    countryCallingCode: "972",
  ),
  CountryModel(
    id: "170",
    name: "Panama",
    status: "PA",
    arabicName: "بنما",
    countryCallingCode: "507",
  ),
  CountryModel(
    id: "171",
    name: "Papua new Guinea",
    status: "PG",
    arabicName: "بابوا غينيا الجديدة",
    countryCallingCode: "675",
  ),
  CountryModel(
    id: "172",
    name: "Paraguay",
    status: "PY",
    arabicName: "باراغواي",
    countryCallingCode: "595",
  ),
  CountryModel(
    id: "173",
    name: "Peru",
    status: "PE",
    arabicName: "بيرو",
    countryCallingCode: "51",
  ),
  CountryModel(
    id: "174",
    name: "Philippines",
    status: "PH",
    arabicName: "الفلبين",
    countryCallingCode: "63",
  ),
  CountryModel(
    id: "175",
    name: "Pitcairn Island",
    status: "PN",
    arabicName: "جزيرة بيتكيرن",
    countryCallingCode: "64",
  ),
  CountryModel(
    id: "176",
    name: "Poland",
    status: "PL",
    arabicName: "بولندا",
    countryCallingCode: "48",
  ),
  CountryModel(
    id: "177",
    name: "Portugal",
    status: "PT",
    arabicName: "البرتغال",
    countryCallingCode: "351",
  ),
  CountryModel(
    id: "178",
    name: "Puerto Rico",
    status: "PR",
    arabicName: "بورتوريكو",
    countryCallingCode: "787",
  ),
  CountryModel(
    id: "179",
    name: "Qatar",
    status: "QA",
    arabicName: "قطر",
    countryCallingCode: "974",
  ),
  CountryModel(
    id: "180",
    name: "Reunion",
    status: "RE",
    arabicName: "ريونيون",
    countryCallingCode: "262",
  ),
  CountryModel(
    id: "181",
    name: "Romania",
    status: "RO",
    arabicName: "رومانيا",
    countryCallingCode: "40",
  ),
  CountryModel(
    id: "182",
    name: "Russia",
    status: "RU",
    arabicName: "روسيا",
    countryCallingCode: "7",
  ),
  CountryModel(
    id: "183",
    name: "Rwanda",
    status: "RW",
    arabicName: "رواندا",
    countryCallingCode: "250",
  ),
  CountryModel(
    id: "184",
    name: "Saint Helena",
    status: "SH",
    arabicName: "سانت هيلينا",
    countryCallingCode: "290",
  ),
  CountryModel(
    id: "185",
    name: "Saint Kitts And Nevis",
    status: "KN",
    arabicName: "سانت كيتس ونيفيس",
    countryCallingCode: "1 869",
  ),
  CountryModel(
    id: "186",
    name: "Saint Lucia",
    status: "LC",
    arabicName: "سانت لوسيا",
    countryCallingCode: "758",
  ),
  CountryModel(
    id: "187",
    name: "Saint Pierre and Miquelon",
    status: "PM",
    arabicName: "سانت بيير وميكولون",
    countryCallingCode: "508",
  ),
  CountryModel(
    id: "188",
    name: "Saint Vincent And The Grenadines",
    status: "VC",
    arabicName: "سانت فينسنت وجزر غرينادين",
    countryCallingCode: "1 784",
  ),
  CountryModel(
    id: "189",
    name: "Saint Barthelemy",
    status: "BL",
    arabicName: "سانت بارتيليمي",
    countryCallingCode: "590",
  ),
  CountryModel(
    id: "190",
    name: "Saint Martin (French)",
    status: "MF",
    arabicName: "سانت مارتن (الجزء الفرنسي)",
    countryCallingCode: "590",
  ),
  CountryModel(
    id: "191",
    name: "Samoa",
    status: "WS",
    arabicName: "ساموا",
    countryCallingCode: "685",
  ),
  CountryModel(
    id: "192",
    name: "San Marino",
    status: "SM",
    arabicName: "سان مارينو",
    countryCallingCode: "378",
  ),
  CountryModel(
    id: "193",
    name: "Sao Tome and Principe",
    status: "ST",
    arabicName: "ساو تومي وبرينسيبي",
    countryCallingCode: "239",
  ),
  CountryModel(
    id: "194",
    name: "Saudi Arabia",
    status: "SA",
    arabicName: "المملكة العربية السعودية",
    countryCallingCode: "966",
  ),
  CountryModel(
    id: "195",
    name: "Senegal",
    status: "SN",
    arabicName: "السنغال",
    countryCallingCode: "221",
  ),
  CountryModel(
    id: "196",
    name: "Serbia",
    status: "RS",
    arabicName: "صربيا",
    countryCallingCode: "381",
  ),
  CountryModel(
    id: "197",
    name: "Seychelles",
    status: "SC",
    arabicName: "سيشيل",
    countryCallingCode: "248",
  ),
  CountryModel(
    id: "198",
    name: "Sierra Leone",
    status: "SL",
    arabicName: "سيراليون",
    countryCallingCode: "232",
  ),
  CountryModel(
    id: "199",
    name: "Singapore",
    status: "SG",
    arabicName: "سنغافورة",
    countryCallingCode: "65",
  ),
  CountryModel(
    id: "200",
    name: "Slovakia",
    status: "SK",
    arabicName: "سلوفاكيا",
    countryCallingCode: "421",
  ),
  CountryModel(
    id: "201",
    name: "Slovenia",
    status: "SI",
    arabicName: "سلوفينيا",
    countryCallingCode: "386",
  ),
  CountryModel(
    id: "202",
    name: "Solomon Islands",
    status: "SB",
    arabicName: "جزر سليمان",
    countryCallingCode: "677",
  ),
  CountryModel(
    id: "203",
    name: "Somalia",
    status: "SO",
    arabicName: "الصومال",
    countryCallingCode: "252",
  ),
  CountryModel(
    id: "204",
    name: "South Africa",
    status: "ZA",
    arabicName: "جنوب أفريقيا",
    countryCallingCode: "27",
  ),
  CountryModel(
    id: "205",
    name: "South Georgia",
    status: "GB",
    arabicName: "جورجيا الجنوبية",
    countryCallingCode: "500",
  ),
  CountryModel(
    id: "206",
    name: "South Sudan",
    status: "SS",
    arabicName: "جنوب السودان",
    countryCallingCode: "211",
  ),
  CountryModel(
    id: "207",
    name: "Spain",
    status: "ES",
    arabicName: "إسبانيا",
    countryCallingCode: "34",
  ),
  CountryModel(
    id: "208",
    name: "Sri Lanka",
    status: "LK",
    arabicName: "سريلانكا",
    countryCallingCode: "94",
  ),
  CountryModel(
    id: "209",
    name: "Sudan",
    status: "SD",
    arabicName: "السودان",
    countryCallingCode: "249",
  ),
  CountryModel(
    id: "210",
    name: "Suriname",
    status: "SR",
    arabicName: "سورينام",
    countryCallingCode: "597",
  ),
  CountryModel(
    id: "211",
    name: "Svalbard And Jan Mayen Islands",
    status: "SJ",
    arabicName: "سفالبارد وجان مايان",
    countryCallingCode: "47 79",
  ),
  CountryModel(
    id: "212",
    name: "Swaziland",
    status: "SZ",
    arabicName: "سوازيلاند",
    countryCallingCode: "268",
  ),
  CountryModel(
    id: "213",
    name: "Sweden",
    status: "SE",
    arabicName: "السويد",
    countryCallingCode: "46",
  ),
  CountryModel(
    id: "214",
    name: "Switzerland",
    status: "CH",
    arabicName: "سويسرا",
    countryCallingCode: "41",
  ),
  CountryModel(
    id: "215",
    name: "Syria",
    status: "SY",
    arabicName: "سوريا",
    countryCallingCode: "963",
  ),
  CountryModel(
    id: "216",
    name: "Taiwan",
    status: "TW",
    arabicName: "تايوان",
    countryCallingCode: "886",
  ),
  CountryModel(
    id: "217",
    name: "Tajikistan",
    status: "TJ",
    arabicName: "طاجيكستان",
    countryCallingCode: "992",
  ),
  CountryModel(
    id: "218",
    name: "Tanzania",
    status: "TZ",
    arabicName: "تانزانيا",
    countryCallingCode: "259",
  ),
  CountryModel(
    id: "219",
    name: "Thailand",
    status: "TH",
    arabicName: "تايلاند",
    countryCallingCode: "66",
  ),
  CountryModel(
    id: "220",
    name: "Togo",
    status: "TG",
    arabicName: "توغو",
    countryCallingCode: "228",
  ),
  CountryModel(
    id: "221",
    name: "Tokelau",
    status: "TK",
    arabicName: "توكيلاو",
    countryCallingCode: "690",
  ),
  CountryModel(
    id: "222",
    name: "Tonga",
    status: "TO",
    arabicName: "تونغا",
    countryCallingCode: "676",
  ),
  CountryModel(
    id: "223",
    name: "Trinidad And Tobago",
    status: "TT",
    arabicName: "ترينيداد وتوباغو",
    countryCallingCode: "1 868",
  ),
  CountryModel(
    id: "224",
    name: "Tunisia",
    status: "TN",
    arabicName: "تونس",
    countryCallingCode: "216",
  ),
  CountryModel(
    id: "225",
    name: "Turkey",
    status: "TR",
    arabicName: "تركيا",
    countryCallingCode: "90",
  ),
  CountryModel(
    id: "226",
    name: "Turkmenistan",
    status: "TK",
    arabicName: "تركمانستان",
    countryCallingCode: "993",
  ),
  CountryModel(
    id: "227",
    name: "Turks And Caicos Islands",
    status: "TC",
    arabicName: "جزر توركس وكايكوس",
    countryCallingCode: "1 649",
  ),
  CountryModel(
    id: "228",
    name: "Tuvalu",
    status: "TV",
    arabicName: "توفالو",
    countryCallingCode: "688",
  ),
  CountryModel(
    id: "229",
    name: "Uganda",
    status: "UG",
    arabicName: "أوغندا",
    countryCallingCode: "256",
  ),
  CountryModel(
    id: "230",
    name: "Ukraine",
    status: "UA",
    arabicName: "أوكرانيا",
    countryCallingCode: "380",
  ),
  CountryModel(
    id: "231",
    name: "United Arab Emirates",
    status: "AE",
    arabicName: "الإمارات العربية المتحدة",
    countryCallingCode: "971",
  ),
  CountryModel(
    id: "232",
    name: "United Kingdom",
    status: "GB",
    arabicName: "المملكة المتحدة",
    countryCallingCode: "44",
  ),
  CountryModel(
    id: "233",
    name: "United States",
    status: "US",
    arabicName: "الولايات المتحدة",
    countryCallingCode: "1",
  ),
  CountryModel(
    id: "234",
    name: "United States Minor Outlying Islands",
    status: "UM",
    arabicName: "جزر الولايات المتحدة النائية",
    countryCallingCode: "581",
  ),
  CountryModel(
    id: "235",
    name: "Uruguay",
    status: "UY",
    arabicName: "أوروغواي",
    countryCallingCode: "598",
  ),
  CountryModel(
    id: "236",
    name: "Uzbekistan",
    status: "UZ",
    arabicName: "أوزبكستان",
    countryCallingCode: "998",
  ),
  CountryModel(
    id: "237",
    name: "Vanuatu",
    status: "VU",
    arabicName: "فانواتو",
    countryCallingCode: "678",
  ),
  CountryModel(
    id: "238",
    name: "Vatican City State (Holy See)",
    status: "VA",
    arabicName: "الفاتيكان",
    countryCallingCode: "379",
  ),
  CountryModel(
    id: "239",
    name: "Venezuela",
    status: "VE",
    arabicName: "فنزويلا",
    countryCallingCode: "58",
  ),
  CountryModel(
    id: "240",
    name: "Vietnam",
    status: "VN",
    arabicName: "فيتنام",
    countryCallingCode: "84",
  ),
  CountryModel(
    id: "241",
    name: "Virgin Islands (British)",
    status: "VG",
    arabicName: "جزر العذراء البريطانية",
    countryCallingCode: "284",
  ),
  CountryModel(
    id: "242",
    name: "Virgin Islands (US)",
    status: "VI",
    arabicName: "جزر العذراء الأمريكية",
    countryCallingCode: "340",
  ),
  CountryModel(
    id: "243",
    name: "Wallis And Futuna",
    status: "WF",
    arabicName: "واليس وفوتونا",
    countryCallingCode: "681",
  ),
  CountryModel(
    id: "244",
    name: "Western Sahara",
    status: "EH",
    arabicName: "الصحراء الغربية",
    countryCallingCode: "212",
  ),
  CountryModel(
    id: "245",
    name: "Yemen",
    status: "YE",
    arabicName: "اليمن",
    countryCallingCode: "967",
  ),
  CountryModel(
    id: "246",
    name: "Zambia",
    status: "ZM",
    arabicName: "زامبيا",
    countryCallingCode: "260",
  ),
  CountryModel(
    id: "247",
    name: "Zimbabwe",
    status: "ZW",
    arabicName: "زمبابوي",
    countryCallingCode: "263",
  ),
  CountryModel(
    id: "248",
    name: "Kosovo",
    status: "XK",
    arabicName: "كوسوفو",
    countryCallingCode: "383",
  ),
  CountryModel(
    id: "249",
    name: "Curaçao",
    status: "CW",
    arabicName: "كوراساو",
    countryCallingCode: "599 9",
  ),
  CountryModel(
    id: "250",
    name: "Sint Maarten (Dutch part)",
    status: "SX",
    arabicName: "سينت مارتن (الجزء الهولندي)",
    countryCallingCode: "383",
  ),
];
